---
- name: Deploy to Kubernetes
  hosts: localhost
  vars:
    env: default
  tasks:
  - name: Start minikube
    command: minikube start --vm-driver=docker --insecure-registry="registry.local"
    any_errors_fatal: true

  - name: Enable ingress
    command: minikube addons enable ingress
    any_errors_fatal: true
  
  - name: Sleep for 30 seconds
    pause:
      seconds: 30

- import_playbook: deploy-namespaces.yaml

- import_playbook: deploy-registry.yaml 

- hosts: localhost
  tasks:
  - name: Sleep for 10 seconds
    pause:
      seconds: 10

- import_playbook: deploy-app.yaml
